### ISSUE TITLE
Tiles are not perfectly aligned 

### ISSUE THREAD

**Issue by abhamacher** [BIOP/ijp-operetta-importer#27]
Hi guys,

I recently assisted two research groups at our university in stitching of Operetta multi-tile image data. Of course I recommended your fantastic plugin for this. However, I cannot really get a perfect stitching out of the plugin for those two work groups. Their samples differ a lot, but the stitching issue seems the same. The alignment is incorrect, but I'm unsure how to solve that. I'm using the script from @lacan ([https://gist.github.com/lacan/cb2eaba47ad001c49b7c232dc6313de9](https://gist.github.com/lacan/cb2eaba47ad001c49b7c232dc6313de9)) but even with the correction factor I can't really improve the result. One example:

![ali_root_example_stitched](https://user-images.githubusercontent.com/61734239/232812487-356c9f9f-f72e-4079-9e1f-190e5e9afeae.PNG)

I uploaded the raw data of one measurement, the used script and two example output images [in sciebo for you.](https://uni-duesseldorf.sciebo.de/s/LRUqeu14sw1K1v6) Would by great if you could have a look at this. I also uploaded the Harmony overview of stitched positions, where you can see that in Harmony everything looks fine. There you can also see that the single tiles are not perfectly in line, but I thought this is covered by the orientation matrix and location details in the index.xml file?

Would be really great, if you could give me a hint how to solve this.

Thanks a lot, Anna

**Comment by NicoKiaru** [comment]
The operetta importer does not perform a 'proper stitching'. It just relies on stage metadata, which is not so bad but won't be precise at the pixel level.

One way to do a good stitching would be to export individual tiles (acquired with significant overlap) and then use another software for stitching (in Fiji: grid collection stitching or BigStitcher). This probably requires a bit of work because I do not know how the stage information will be properly passed to these plugins.

**Comment by lacan** [comment]
closing for lack of update. Considered resolved. Nothing to fix
