### ISSUE TITLE
Stitching Archived Data with Operetta Importer

### ISSUE THREAD

**Issue by jamila-griffith** [BIOP/ijp-operetta-importer#30]
Hi,

There was a post talking about reading Archived data directly into FIJI using Operetta Importer. 

https://github.com/BIOP/ijp-operetta-importer/issues/17#issuecomment-1969365813

Just wondering if that is part of the BIOP plugin now or a separate script?

Thanks

**Comment by NicoKiaru** [comment]
Hello @jamila-griffith , 

No it's the same, no extra script. However the archive reading only work with the latest versions of Harmony. In short, just try with your archive, and if it doesn't work it's most probably because the archive format is too old.

You can also share a small archive and I can tell you if there's a chance for it to work.
